### ISSUE TITLE
tableToJava函数不够通用

### ISSUE THREAD

**Issue by zcwdlove** [zlt2000/microservices-platform#1]
https://github.com/zlt2000/microservices-platform/blob/5d4c30df4b800cd24f948f32ea2e168d210365be/zlt-business/code-generator/src/main/java/com/central/generator/utils/GenUtils.java#L173

一般数据库表名都会以t_xxx, t_xxx_yyy格式命名，replace函数是将tablePrefix替换成""，但如果有张表名为: t_event_message, 生成java文件就会出现EvenMessage, 这显然不是我们想要的结果，可以考虑这样改进： tableName = tableName.substring(tablePrefix.length(), tableName.length());

**Comment by zlt2000** [comment]
已经修复
