### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by yimxingbo** [zlt2000/microservices-platform#24]
线上文档为什么要收费才能看哈。。

**Comment by zlt2000** [comment]
前三章是免费的，足够完全支撑项目的部署、启动和使用

发送自 Windows 10 版邮件应用

发件人: yimxingbo
发送时间: 2021年4月22日 13:38
收件人: zlt2000/microservices-platform
抄送: Subscribed
主题: [zlt2000/microservices-platform] 文档 (#24)

线上文档为什么要收费才能看哈。。
