### ISSUE TITLE
有封装打包和启停脚本吗

### ISSUE THREAD

**Issue by zhbdesign** [zlt2000/microservices-platform#26]
有封装打包和启停脚本吗

**Comment by zhbdesign** [comment]
> 有封装打包和启停脚本吗

打成
bin/
config/
logs/
这种结构的包，bin包含启停脚本，config包含配置文件，logs包含运行日志文件

**Comment by zlt2000** [comment]
打包用maven，你发的这些结构我没看出来和打包有关系，不是自己手动创建一次就可以了吗？又不需要每次打包都创建这些
