### ISSUE TITLE
微服务调用时，日志服务无法拿到traceId

### ISSUE THREAD

**Issue by pikefeier** [zlt2000/microservices-platform#44]
zlt-log中，WebTraceFilter类上的注解@Component并没有起作用，导致在微服务调用时，并没有走OncePerRequestFilter的代码逻辑。将@Component注释，把这个类放入spring.factories中，在被调用微服务中打印日志，可以显示traceId。
--以上是个人见解，如果有理解错误，请批评指正，谢谢

**Comment by zlt2000** [comment]
请问是否有修改过代码，LogAutoConfigure会扫描路径下的所有 component

**Comment by pikefeier** [comment]
嗯，是我这里LogAutoConfigure启动类上没有配置@ComponentScan，已经解决，谢谢
