### ISSUE TITLE
redis 设置过期时间问题

### ISSUE THREAD

**Issue by pikefeier** [zlt2000/microservices-platform#46]
/**
     * 一次性添加数组到   过期时间的  缓存，不用多次连接，节省开销
     *
     * @param keys   redis主键数组
     * @param values 值数组
     * @param time   过期时间(单位秒)
     */
    public void setExpire(final String[] keys, final Object[] values, final long time) {
        for (int i = 0; i < keys.length; i++) {
            redisTemplate.opsForValue().set(keys[i], values[i], time, TimeUnit.SECONDS);
        }
    }
上述代码：怎么做到不用多次连接，节省开销？

**Comment by zlt2000** [comment]
可以用pipeline
